apiVersion: v1   
kind: Service
metadata:
  name: tomcat-service
  labels:
    app: tomcat-service
spec:
  type: NodePort
  selector:                       # 选择标签  匹配的是deployment容器标签
    app: tomcat-deployment        # 匹配 tomcat-deployment    
  ports:
  - port: 8000                   # 暴露给集群内客户访问服务
    targetPort: 8080             # pod上的真实端口
    nodePort: 32500              # 对外暴露的端口号，对外提供访问的端口，暴露给集群外客户访问服务