apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-depl
  name: demo-depl
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-depl
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-depl
    spec:
      containers:
      - image: 192.168.101.102/wang_ning_test/demo_jar:v1.0.0
        name: demo-jar-g7vsv
        resources: {}
      imagePullSecrets:    # 这里是拉取镜像时所使用的账户
      - name: login-harbor # secret.yaml 中name
status: {}

