apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: demo-jar
    image: 192.168.101.102/wang_ning_test/demo_jar:v1.0.0
    env:
      - name: SECRET_USERNAME  # 用户名的名字
        valueFrom:                         # 以变量形式挂载
          secretKeyRef:
            name: demo-secret    # mysecret 为 Secret 的 name
            key: username      # key 值为 
      - name: SECRET_PASSWORD  # 密码的名字 
        valueFrom:
          secretKeyRef:
            name: demo-secret
            key: password
