apiVersion: v1    #Api接口版本
kind: Secret       #定义控制器
metadata:          #信息
  name: login-harbor      #Sectet 名称
type: kubernetes.io/dockerconfigjson    #用来创建用户docker registry认证的Secret
data:
   #这里添加加密后的密钥
     .dockerconfigjson: ewoJImF1dGhzIjogewoJCSIxOTIuMTY4LjEwMS4xMDIiOiB7CgkJCSJhdXRoIjogIllXUnRhVzQ2U0dGeVltOXlNVEl6TkRVPSIKCQl9Cgl9LAoJIkh0dHBIZWFkZXJzIjogewoJCSJVc2VyLUFnZW50IjogIkRvY2tlci1DbGllbnQvMTguMDYuMy1jZSAobGludXgpIgoJfQp9
