apiVersion: v1                  # 指定api版本，此值必须在kubectl api-versions中
kind: Service                   # 指定创建资源的角色/类型 
metadata:
  name: demo-service            # 资源的名字，在同一个namespace中必须唯一
  namespace: default            # 部署在哪个namespace中  
  labels:                       # 设定资源的标签
    app: demo-service
spec:
  type: NodePort                 # 配置 Nodeport 外部流量可访问k8s中的服务
  selector:                      # 选择标签  匹配的是deployment容器标签
    app: demo                    # 匹配 demo   
  ports:
  - port: 8000                   # 暴露给集群内客户访问服务
    targetPort: 8080             # pod上的真实端口
    nodePort: 32500              # 对外暴露的端口号，对外提供访问的端口，暴露给集群外客户访问服务
