kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: roledemo  # 创建当前命名空间的角色
  name: pod-reader
rules:
- apiGroups: [""] # "" 表示核心API组
  resources: ["pods"]  # 资源类型 pods
  verbs: ["get", "watch", "list"] # 用于的权限
