apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2022-09-25T11:40:22Z"
  name: demo-nfs-svc
  namespace: default
  resourceVersion: "238126"
  uid: 2a9c0d5e-56b4-4040-a181-cdacc71fe0f2
spec:
  clusterIP: 10.97.108.101
  clusterIPs:
  - 10.97.108.101
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31194
    port: 8001
    protocol: TCP
    targetPort: 8080
  selector:
    app: demo-nfs
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
