apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 5Gi   # 定义 nfs 服务器容量
  accessModes:     # 定义存储模式
    - ReadWriteMany  
  nfs:
    path: /data/nfs  # 定义存储位置
    server: 192.168.101.103 # 定义 nfs 服务器 ip